name: CI/CD Pipeline

on: [push]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 18 with Adopt distribution
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '18'
      - name: Set permissions for gradlew
        run: chmod +x demo/gradlew
      - name: Run unit tests
        run: |
          cd demo
          ./gradlew test --tests *TestTask

  integration_tests:
    needs: unit_tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run integration tests
        run: |
          cd demo
          ./gradlew test --tests *TestTaskController

  build_and_push:
    needs: integration_tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Packages Docker registry
        run: echo "${{ secrets.DOCKER_PAT_TEST }}" | docker login docker.pkg.github.com -u d1mazik --password-stdin
      - name: Build Docker image
        run: |
          IMAGE_TAG=$(echo ${GITHUB_REF##*/} | tr '[:upper:]' '[:lower:]')
          docker build -t docker.pkg.github.com/d1mazik/to-do-list-grupp-7/min-app:$IMAGE_TAG -f Dockerfile .
      - name: Push Docker image to GitHub Packages
        run: |
          IMAGE_TAG=$(echo ${GITHUB_REF##*/} | tr '[:upper:]' '[:lower:]')
          docker push docker.pkg.github.com/d1mazik/to-do-list-grupp-7/min-app:$IMAGE_TAG

  fake_deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Fake Deploy to Test Environment
        run: |
          IMAGE_TAG=$(echo ${GITHUB_REF##*/} | tr '[:upper:]' '[:lower:]')
          echo "Deploying image docker.pkg.github.com/d1mazik/to-do-list-grupp-7/min-app:$IMAGE_TAG"
